version: "2"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - sync-network
    restart: always
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ProcessQueue:1:1"
    networks:
      - sync-network
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  sync-api:
    build: .
    container_name: sync-api
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    networks:
      - sync-network
    restart: always
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
networks:
  sync-network:
    driver: bridge
